services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\DoctrineRandomBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  Tourze\DoctrineRandomBundle\Service\:
    resource: '../../Service/'

  doctrine-random.property-accessor:
    class: Symfony\Component\PropertyAccess\PropertyAccessor
    factory: [ 'Symfony\Component\PropertyAccess\PropertyAccess', 'createPropertyAccessor' ]
    public: true

  # 配置 Lock Store 和 LockFactory 服务
  lock.store:
    class: Symfony\Component\Lock\Store\InMemoryStore

  Symfony\Component\Lock\LockFactory:
    arguments:
      - '@lock.store'

